# =============================================================================
# HERBARIUM DATA WRANGLING & ANALYSIS
# =============================================================================
# Steps:
#   1. Remove cultivated species
#   2. Remove garden/planted localities
#   3. Fill missing coordinates from Gazetteer
#   4. Extract species names from habitat notes
#   5. Remove non-species rows
#   6. Update/validate species names via Taxonstand
#   7. Create a density map of all collection points
# =============================================================================

# ── Packages ──────────────────────────────────────────────────────────────────
# Install any missing packages automatically
required_pkgs <- c(
  "tidyverse", # data manipulation
  "readxl", # read excel files
  "writexl", # write excel files
  "ggplot2", # plotting
  "sf", # handle spatial data
  "rnaturalearth", # provide high-quality vector data
  "rnaturalearthdata", # provide low- and medi- resolution vector map
  "viridis" # map data & colour scale
)
new_pkgs <- required_pkgs[!required_pkgs %in% installed.packages()[, "Package"]]
if (length(new_pkgs)) {
  install.packages(new_pkgs, dependencies = TRUE)
}

library(tidyverse)
library(readxl)
library(writexl)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)

rm(new_pkgs, required_pkgs) # Tidy

# =============================================================================
# DATA LOADING
# =============================================================================

# NOTE: Save 'Herb_collection_25-09-2023' as CSV UTF-8 first to handle special
# characters correctly. The gazetteer can stay as .xls.
herb <- read.csv(
  "data/Herb_collection_25-09-2023.csv",
  na.strings = c("", "NA")
)

gazet <- read_csv("data/gazetteer.csv")

# =============================================================================
# COLUMN FILTERING & RENAMING
# =============================================================================

herb <- herb |>
  select(
    -c(1:3, 6, 8:12, 14, 15, 19, 21, 22, 29, 31, 33, 35:45, 47:61, 63, 66:97)
  ) |>
  rename(
    id = BRAHMS,
    cat = CATEGORY,
    name = NAMESTRING,
    year = YEAR,
    group = GROUP,
    family = FANAME,
    genus = GENAME,
    spp = FULLNAME,
    country = CONAME,
    major = MAJOR,
    minor = MINOR,
    locality = LOCALITY,
    loc_note = LOCNOTES,
    y = LAT,
    x = LONG,
    xy_unit = LLUNIT,
    xy_source = LLORIG,
    habitat_note = HABITATTXT,
    cul = CULTIVATED,
    cul_note = CULTNOTES,
    notes = NOTES
  )

gazet <- gazet |>
  select(-c(1:4, 16:23)) |>
  rename(
    country = coname,
    y = lat,
    x = long,
    xy_unit = llunit,
    xy_res = llres,
    xy_source = llorig
  )

# Remove rows with no locality data
herb <- herb |> filter(locality != "No loc." | is.na(locality))
gazet <- gazet |> filter(x != 0 | is.na(x))

# =============================================================================
# STEP 1 – Remove cultivated specimens
# =============================================================================

herb <- herb |> filter(!cul %in% "Yes")

# =============================================================================
# STEP 2 – Remove garden / planted localities
# =============================================================================

herb %>% distinct(locality)

garden_localities <- c(
  "University Farm",
  "Pamplemousses Botanic Garden",
  "Curepipe Botanic Garden",
  "Ebène",
  "Curepipe Forestry Nursery",
  "Beau Bassin",
  "Trianon",
  "Queen Elizabeth College",
  "Long Mountain Nursery",
  "Chebelle",
  "Morcellement St. André",
  "Pamplemousses MSIRI station",
  "Government House",
  "Royal Botanic Gardens Pamplemousses",
  "Barkly Experimental Station",
  "Barkly",
  "Nursery NPCS",
  "Champs de Mars",
  "Cassis Nursery",
  "Rose Hill",
  "Rose-Hill",
  "MSIRI",
  "Balfour Garden",
  "Richelieu Experimental Station",
  "Bagatelle",
  "Bagatelle S.E.",
  "Roches Brunes",
  "Curepipe C. L. Arboretum",
  "Bramsthan",
  "Endémika",
  "Anahita"
)

# Ferns are kept even from garden localities
herb <- herb |>
  filter(!(locality %in% garden_localities & group != "fern"))

rm(garden_localities)

# =============================================================================
# STEP 3 – Fill missing coordinates from Gazetteer
# =============================================================================

# Deduplicate gazetteer on locality + minor (keep first occurrence)
gazet_unique <- gazet |>
  group_by(locality, minor) |>
  slice(1) |>
  ungroup()

# Join herbarium + gazetteer and fill missing coordinates
herb <- herb |>
  left_join(
    gazet_unique,
    by = c("locality", "minor"),
    suffix = c(".herb", ".gazet")
  ) |>
  mutate(
    # Final coordinates
    x = coalesce(na_if(x.herb, 0), x.gazet),
    y = coalesce(na_if(y.herb, 0), y.gazet),

    # Track source of coordinates
    coord_source = case_when(
      !is.na(x.herb) & x.herb != 0 ~ "herb",
      (is.na(x.herb) | x.herb == 0) & !is.na(x.gazet) ~ "gazet",
      TRUE ~ "missing"
    ),

    # Merge coordinate metadata
    xy_unit = coalesce(xy_unit.herb, xy_unit.gazet),
    xy_source = coalesce(xy_source.herb, xy_source.gazet)
  ) |>
  select(
    id,
    cat,
    name,
    year,
    group,
    family,
    genus,
    spp,
    country = country.herb,
    major = major.herb,
    minor,
    locality,
    loc_note,
    x,
    y,
    xy_unit,
    xy_source,
    coord_source,
    habitat_note,
    notes
  ) |>
  # Remove rows without coordinates
  filter(
    !is.na(x),
    !is.na(y),
    x != 0,
    y != 0
  ) |>
  # Standardize coordinate precision
  mutate(
    x = round(as.numeric(x), 5),
    y = round(as.numeric(y), 5)
  )

# Inspect final dataset
glimpse(herb)

# Tidy environment
rm(gazet, gazet_unique)

# =============================================================================
# STEP 4 – Extract species names from habitat_note column
# =============================================================================

# Regex: capitalised word followed by a lowercase word (Genus species pattern)
extract_species <- function(note) {
  matches <- str_extract_all(note, "\\b[A-Z][a-z]+\\s[a-z]+\\b")
  sapply(matches, paste, collapse = ", ")
}

# Apply extraction and unnest so each extracted name gets its own row
extracted_data <- herb |>
  mutate(species_names = extract_species(habitat_note)) |>
  mutate(species_names = strsplit(species_names, ", ")) |>
  unnest(species_names) |>
  # Clear fields that are irrelevant for extracted records
  mutate(
    across(
      c(group, family, genus, loc_note, habitat_note, notes, cat, name),
      ~NA
    ),
    source = "H.extract"
  ) |>
  select(-country, -major, -spp) |>
  rename(spp = species_names)

rm(extract_species) # Tidy

# =============================================================================
# STEP 5 – Remove non-species rows
# =============================================================================

unique_species <- extracted_data %>%
  select(spp) %>%
  distinct() %>%
  arrange(spp)

non_species <- c(
  "About one",
  "Abrupt cliffs",
  "Abundant along",
  "Abundant and",
  "Adjacent native",
  "Additional det",
  "Aigrettes can",
  "Almost in",
  "Along bank",
  "Along crestline",
  "Along forest",
  "Along muddy",
  "Along path",
  "Along ridge",
  "Along ridgeline",
  "Along river",
  "Along road",
  "Along roadside",
  "Along steep",
  "Along stream",
  "Along streams",
  "Along the",
  "Along top",
  "Along valley",
  "Along verandah",
  "Along west",
  "Along with",
  "Also in",
  "Also occurs",
  "Also on",
  "Among basalt",
  "Among dense",
  "Among grasses",
  "Among low",
  "Among the",
  "Amongst dense",
  "Amongst grass",
  "An endemic",
  "An extremely",
  "An important",
  "An occasional",
  "An undetermined",
  "Annotation by",
  "Annual phase",
  "Annual rainfall",
  "Another large",
  "Appears to",
  "Aquatic plant",
  "Area heavily",
  "Area invaded",
  "Area weeded",
  "Argent in",
  "Arid soil",
  "Around the",
  "As a",
  "As an",
  "Ascendant up",
  "Asia and",
  "Associated native",
  "Associated species",
  "Associated with",
  "Association of",
  "At all",
  "At base",
  "At edge",
  "At foot",
  "At least",
  "At sea",
  "At summit",
  "At the",
  "At this",
  "Attached to",
  "Abrupt cliffs",
  "Abundant along",
  "Abundant and",
  "Adjacent native",
  "Asteraceae",
  "Baie du",
  "Bamboo hedge",
  "Bank of",
  "Banks of",
  "Basalt cliffs",
  "Basalt islet",
  "Between buttress",
  "Basalt rock",
  "Basalt rocks",
  "Base of",
  "Bassin and",
  "Between rocks",
  "Between the",
  "Big clumps",
  "Bird sanctuary",
  "Boggy area",
  "Boggy ground",
  "Boggy path",
  "Boggy site",
  "Bois a",
  "Bois d",
  "Bord de",
  "Border of",
  "Bottom of",
  "Boulder slope",
  "Boulder strewn",
  "Bouldery region",
  "Bras d",
  "But occurs",
  "But the",
  "By dry",
  "By large",
  "By riverbanks",
  "By road",
  "By roadside",
  "By roadsides",
  "By roadsie",
  "By side",
  "By solar",
  "By steam",
  "By stream",
  "Calcarenite islet",
  "Came from",
  "Cane field",
  "Cane fields",
  "Cane fields",
  "Canefield weed",
  "Canopy reaching",
  "Champagne plateau",
  "Champagne tributary",
  "Champs cultives",
  "Cimatic forest",
  "Clay bank",
  "Clay on",
  "Clay roadside",
  "Clean shallow",
  "Clearing on",
  "Cleft of",
  "Cliff face",
  "Cliffy site",
  "Climax foerst",
  "Climax forest",
  "Climber in",
  "Climber with",
  "Climbing and",
  "Climbing on",
  "Climbing over",
  "Climbing upon",
  "Close to",
  "Closed dry",
  "Closed forest",
  "Cloud forest",
  "Clump of",
  "Clumps are",
  "Clumps growing",
  "Clupm forming",
  "Codominant in",
  "Codominant with",
  "Coin de",
  "Collected in",
  "Collected near",
  "Collected on",
  "College of",
  "Colonizing more",
  "Colonizing open",
  "Colony growing",
  "Colony on",
  "Colony spread",
  "Color pale",
  "Combo regions",
  "Common along",
  "Common amongst",
  "Common around",
  "Common at",
  "Common by",
  "Common cane",
  "Common epiphyte",
  "Common everywhere",
  "Common from",
  "Common grass",
  "Common in",
  "Common littoral",
  "Common locally",
  "Common on",
  "Common roadside",
  "Common round",
  "Common savannah",
  "Common species",
  "Common understorey",
  "Common upland",
  "Common weed",
  "Commonin grass",
  "Commonly cultivated",
  "Commun dans",
  "Comon in",
  "Compact vegetation",
  "Completely exposed",
  "Confined to",
  "Coral five",
  "Coral sand",
  "Covering ground",
  "Creeper on",
  "Creeping in",
  "Creeping on",
  "Creeping over",
  "Creeping plant",
  "Creepping over",
  "Crescit in",
  "Crete rocheuse",
  "Croit dans",
  "Croit sur",
  "Crop museum",
  "Cultivated as",
  "Cultivated in",
  "Cultivated at",
  "Cultivated ornamental",
  "Cultivation in",
  "Curepipe and",
  "Curepipe growing",
  "Curepipe in",
  "Cut over",
  "Cyathea stem",
  "Damp area",
  "Damp horizontal",
  "Dans les",
  "Dappled shade",
  "Daruty de",
  "Dead black",
  "Debased indigenous",
  "Decumbent over",
  "Deep fissures",
  "Deep weedy",
  "Degraded cloud",
  "Degraded forest",
  "Degraded lower",
  "Degraded native",
  "Degraded upland",
  "Degraded vegetation",
  "Degraded vestige",
  "Degraded wet",
  "Dense climax",
  "Dense clump",
  "Dense dwarf",
  "Dense forest",
  "Dense forests",
  "Dense humid",
  "Dense indigenous",
  "Dense low",
  "Dense native",
  "Dense primary",
  "Dense shade",
  "Dense shady",
  "Dense thicket",
  "Dense wet",
  "Deserted gardens",
  "Destroyed forest",
  "Disturb upland",
  "Disturbed and",
  "Disturbed degraded",
  "Disturbed forest",
  "Disturbed invaded",
  "Disturbed shrubby",
  "Disturbed upland",
  "Disturbed vegetatiion",
  "Disturbed vegetation",
  "Does not",
  "Dominant constituent",
  "Dominant constituents",
  "Dominant exotic",
  "Dominant in",
  "Dominant species",
  "Dominat crest",
  "Dried out",
  "Dried up",
  "Drier part",
  "Drier parts",
  "Drier regions",
  "Dry association",
  "Dry escarpments",
  "Dry exposed",
  "Dry forest",
  "Dry localities",
  "Dry locality",
  "Dry native",
  "Dry open",
  "Dry parts",
  "Dry primary",
  "Dry regions",
  "Dry rocky",
  "Dry situations",
  "Dry slope",
  "Dry slopes",
  "Dry stony",
  "Dryish primary",
  "Dune and",
  "Dwarf forest",
  "Dwarf heath",
  "Dwarf vegetation",
  "East of",
  "East part",
  "Eastern flank",
  "Eastern footslope",
  "Eastern littoral",
  "Eastern side",
  "Eau near",
  "Ebenaceae dominant",
  "Ebeniers et",
  "Ebony thicket",
  "Edge of",
  "Elongate patches",
  "Endroit de",
  "Entre les",
  "Environs de",
  "Environs habitations",
  "Ephipyte in",
  "Epilithe sur",
  "Epiphitic on",
  "Epiphyte dans",
  "Epiphyte growing",
  "Epiphyte in",
  "Epiphyte near",
  "Epiphyte on",
  "Epiphyte sur",
  "Epiphytic fern",
  "Epiphytic on",
  "Epiphytic orchid",
  "Ericaceae sur",
  "Especially in",
  "Estate in",
  "Estate private",
  "Evergreen dry",
  "Evergreen forest",
  "Evergreen wet",
  "Everywhere in",
  "Exotic present",
  "Exotic species",
  "Exotic thicket",
  "Exotics incl",
  "Exotics nearby",
  "Exotics present",
  "Experimental plot",
  "Exposed cliffs",
  "Exposed site",
  "Exposed sites",
  "Exposed situation",
  "Exposed situations",
  "Exposed to",
  "Exposition mi",
  "Extremely common",
  "Extremely rare",
  "Fairly common",
  "Fairly dense",
  "Fairly frequent",
  "Fairly sheltered",
  "Fairly wide",
  "Fallow sugar",
  "Feeder stream",
  "Fern growing",
  "Few clumps",
  "Few individuals",
  "Few native",
  "Few plants",
  "Fewer and",
  "Five adult",
  "Fields near",
  "Flacq and",
  "Flank of",
  "Flat slope",
  "Floating in",
  "Florin plot",
  "Flowers and",
  "Flowers of",
  "Flowers or",
  "Flowers present",
  "Flycatcher site",
  "Fodder grass",
  "Foot of",
  "Foot slopes",
  "Foothills of",
  "Footslopes of",
  "Forest area",
  "Forest degraded",
  "Forest invaded",
  "Forest much",
  "Forest on",
  "Forest plantation",
  "Forest plantations",
  "Forest quarters",
  "Forest region",
  "Forest remnants",
  "Forest station",
  "Forest stream",
  "Forest swamp",
  "Forest undergrowth",
  "Forest with",
  "Forested area",
  "Forestry department",
  "Forests at",
  "Forests of",
  "Foret basse",
  "Forets de",
  "Forets du",
  "Forets humides",
  "Formation arbustive",
  "Forming clumps",
  "Forming colony",
  "Forming dense",
  "Forming isolated",
  "Forming large",
  "Forming small",
  "Forming sward",
  "Forms savannah",
  "Forms savannahs",
  "Found all",
  "Found at",
  "Found behind",
  "Found growing",
  "Found in",
  "Found on",
  "Four examples",
  "Frequent in",
  "Frequent near",
  "Frequent on",
  "Frequently in",
  "Frequently planted",
  "Fresh water",
  "From roadsides",
  "From top",
  "Fronds pendant",
  "Fruits observed",
  "Full of",
  "Full sun",
  "Full sunlight",
  "Fully exposed",
  "Garden at",
  "Geometriques on",
  "Good quality",
  "Gorges de",
  "Governement dairy",
  "Gowing at",
  "Gowing in",
  "Grass growing",
  "Grass on",
  "Grassland and",
  "Grassy area",
  "Grassy exposed",
  "Grassy places",
  "Grassy plains",
  "Grassy roadside",
  "Grassy vegetation",
  "Gregarious along",
  "Groiwng by",
  "Ground fern",
  "Ground flora",
  "Ground in",
  "Ground on",
  "Ground rooting",
  "Ground variable",
  "Ground waterlogged",
  "Grounds of",
  "Growig in",
  "Growing afloat",
  "Growing all",
  "Growing almost",
  "Growing along",
  "Growing among",
  "Growing amongst",
  "Growing anthropogenic",
  "Growing approx",
  "Growing around",
  "Growing as",
  "Growing association",
  "Growing at",
  "Growing between",
  "Growing by",
  "Growing clos",
  "Growing close",
  "Growing closer",
  "Growing dead",
  "Growing decumbent",
  "Growing edge",
  "Growing forest",
  "Growing from",
  "Growing growing",
  "Growing in",
  "Growing inside",
  "Growing mainly",
  "Growing mostly",
  "Growing near",
  "Growing next",
  "Growing on",
  "Growing out",
  "Growing outside",
  "Growing over",
  "Growing parasitically",
  "Growing preserved",
  "Growing protected",
  "Growing sloppy",
  "Growing the",
  "Growing through",
  "Growing under",
  "Growing up",
  "Growing very",
  "Growing wild",
  "Growing with",
  "Growng in",
  "Grows in",
  "Grows mostly",
  "Grows on",
  "Grows together",
  "Grows wild",
  "Habitat and",
  "Half way",
  "Hanging on",
  "Healthland overrun",
  "Heath association",
  "Heath associes",
  "Heath assoecies",
  "Heath community",
  "Heath flora",
  "Heath forest",
  "Heath formation",
  "Heath land",
  "Heath vegetation",
  "Heathland entirely",
  "Heathland on",
  "Herb growing",
  "Herb in",
  "Herb rooting",
  "Herb scandant",
  "Herb scrambling",
  "High and",
  "High forest",
  "High growing",
  "High levels",
  "High on",
  "High rainfall",
  "High stations",
  "Highly invaded",
  "Hill near",
  "Hot drier",
  "However also",
  "Humid habitat",
  "Humid regions",
  "Humid situations",
  "Ile aux",
  "In a",
  "In abundance",
  "In agricultural",
  "In an",
  "In assocaition",
  "In association",
  "In bambou",
  "In black",
  "In boggy",
  "In boulder",
  "In brackish",
  "In calcareous",
  "In campis",
  "In cane",
  "In canefields",
  "In cave",
  "In cavity",
  "In cemetry",
  "In clariere",
  "In clayey",
  "In clearing",
  "In clearings",
  "In climax",
  "In coastal",
  "In compact",
  "In crevice",
  "In crevices",
  "In cultivated",
  "In cultivation",
  "In damp",
  "In dark",
  "In debris",
  "In deep",
  "In degraded",
  "In dense",
  "In densely",
  "In deposited",
  "In disturbed",
  "In ditches",
  "In drainage",
  "In drier",
  "In dry",
  "In every",
  "In exotic",
  "In experimental",
  "In exposed",
  "In field",
  "In fields",
  "In fine",
  "In first",
  "In flower",
  "In forest",
  "In forests",
  "In fork",
  "In full",
  "In fully",
  "In garden",
  "In gardens",
  "In good",
  "In grass",
  "In grassland",
  "In grassy",
  "In gravelly",
  "In grey",
  "In ground",
  "In health",
  "In heath",
  "In heavy",
  "In high",
  "In hummus",
  "In humus",
  "In immediate",
  "In indigenous",
  "In intact",
  "In intermediate",
  "In isolated",
  "In labourdonnaisia",
  "In lawns",
  "In light",
  "In localised",
  "In localized",
  "In low",
  "In lowlands",
  "In mangrove",
  "In many",
  "In marsh",
  "In marshes",
  "In marshy",
  "In meadows",
  "In mixed",
  "In moderate",
  "In moist",
  "In moss",
  "In muddy",
  "In native",
  "In near",
  "In open",
  "In orchard",
  "In parcel",
  "In partial",
  "In patch",
  "In paths",
  "In pine",
  "In plains",
  "In private",
  "In quiet",
  "In region",
  "In regions",
  "In remnants",
  "In rich",
  "In river",
  "In rock",
  "In rocky",
  "In salt",
  "In sand",
  "In sandy",
  "In savannah",
  "In scrub",
  "In scrubland",
  "In secondary",
  "In several",
  "In shade",
  "In shaded",
  "In shady",
  "In shallow",
  "In shrub",
  "In similar",
  "In slow",
  "In soil",
  "In southlands",
  "In sparse",
  "In stagnant",
  "In stone",
  "In sub",
  "In sugar",
  "In sugarcane",
  "In swamps",
  "In swiftly",
  "In tea",
  "In the",
  "In thicket",
  "In thickets",
  "In this",
  "In thorn",
  "In transitional",
  "In understorey",
  "In upland",
  "In valley",
  "In vegetable",
  "In very",
  "In warmer",
  "In waste",
  "In water",
  "In wet",
  "In windy",
  "In wood",
  "In woods",
  "In yard",
  "Inavded upland",
  "Indense insigenous",
  "Indigenous bushes",
  "Indigenous forest",
  "Indigenous growing",
  "Indigenous heath",
  "Indigenous low",
  "Indigenous scrub",
  "Indigenous thicket",
  "Indigenous thickets",
  "Inside crater",
  "Inside forest",
  "Inside sugarcane",
  "Inside tea",
  "Intermediate conditions",
  "Intermediate dry",
  "Intermediate forest",
  "Interspersed with",
  "Interstices of",
  "Introduced by",
  "Invaded and",
  "Invaded areas",
  "Invaded by",
  "Invaded forest",
  "Invaded heath",
  "Invaded principally",
  "Invaded region",
  "Invaded shrubby",
  "Invaded upland",
  "Invaded with",
  "Invading arable",
  "Invading cyclone",
  "Invading indigenous",
  "Invading plant",
  "Invasion by",
  "Invasive plant",
  "Invasive present",
  "Invasive tall",
  "Isolated clump",
  "Isolated clumps",
  "Isolated tree",
  "It appears",
  "It was",
  "Julien d",
  "Just above",
  "Just behind",
  "Just below",
  "Just outside",
  "Large expanses",
  "Largest native",
  "Laterite soil",
  "Lateritesoil with",
  "Lateritic soil",
  "Lawn weed",
  "Le pouce",
  "Leaf sample",
  "Les cretes",
  "Les parties",
  "Les plantes",
  "Liana growing",
  "Liane climbing",
  "Lies ca",
  "Light shade",
  "Light to",
  "Lightly invaded",
  "Littoral vegetation",
  "Littotal vegetation",
  "Loam soil",
  "Local varieties",
  "Localised clustered",
  "Localised population",
  "Localite seche",
  "Localized fern",
  "Locally also",
  "Locally codominant",
  "Locally common",
  "Locally domiant",
  "Locally very",
  "Located in",
  "Longue near",
  "Lorence on",
  "Lorence showing",
  "Lots of",
  "Louis and",
  "Louis side",
  "Low altitude",
  "Low and",
  "Low cloud",
  "Low degraded",
  "Low disturbed",
  "Low dryish",
  "Low ericoid",
  "Low evergreen",
  "Low forest",
  "Low heath",
  "Low indigenous",
  "Low land",
  "Low level",
  "Low levels",
  "Low mixed",
  "Low mossy",
  "Low native",
  "Low primary",
  "Low rainfall",
  "Low ridge",
  "Low rocky",
  "Low scrub",
  "Low shrubby",
  "Low stunted",
  "Low thicket",
  "Low to",
  "Low upland",
  "Low wet",
  "Low windswept",
  "Low woodland",
  "Lower montane",
  "Lower regions",
  "Lower slopes",
  "Lowland dry",
  "Lowland forest",
  "Lowland forests",
  "Lowland grass",
  "Lowland native",
  "Lowland regions",
  "Lowland scrubs",
  "Lowland upland",
  "Lowlands and",
  "Lying on",
  "Macabe before",
  "Main component",
  "Main invader",
  "Main stems",
  "Mainly on",
  "Malherbe forest",
  "Mamelles mt",
  "Manglier tree",
  "Many clumps",
  "Mare aux",
  "Mares and",
  "Marsh bordered",
  "Marsh heathland",
  "Marsh land",
  "Marsh plant",
  "Marsh scattered",
  "Marshes and",
  "Marshy area",
  "Marshy ground",
  "Marshy grounds",
  "Marshy heathland",
  "Marshy land",
  "Marshy lands",
  "Marshy localities",
  "Marshy locality",
  "Marshy site",
  "Marshy situations",
  "Marshy soil",
  "Mature evergreen",
  "Mature lower",
  "Mature transitional",
  "Mature wet",
  "Mauritian plants",
  "May be",
  "Medium altitudes",
  "Medium and",
  "Middle of",
  "Milieu de",
  "Mixed forest",
  "Mixed scrub",
  "Mixed wet",
  "Moderate partial",
  "Moderate shade",
  "Moist mid",
  "Moist ravine",
  "Moka and",
  "Moka et",
  "Mondrain to",
  "Monogramma and",
  "Montagne de",
  "Montane wet",
  "More common",
  "More frequent",
  "More or",
  "Mossy forest",
  "Mossy rainforest",
  "Motorway banks",
  "Mountain and",
  "Mountain area",
  "Mountain next",
  "Mountain reserves",
  "Mt invaded",
  "Much invaded",
  "Much used",
  "Mud dried",
  "Muddy forest",
  "Muddy water",
  "Murraya and",
  "Murraya etc",
  "Musa cf",
  "Musa sp",
  "Must have",
  "Myrtaceae association",
  "Myrtaceae formation",
  "Myrtaceae in",
  "Mysorensis and",
  "NA",
  "Names updated",
  "Natiev plants",
  "Native forest",
  "Native forests",
  "Native frorest",
  "Native palm",
  "Native plant",
  "Native plants",
  "Native present",
  "Native remnants",
  "Native scrub",
  "Native species",
  "Native thicket",
  "Native thickets",
  "Native understorey",
  "Native upland",
  "Natives present",
  "Naturalise a",
  "Naturalised and",
  "Naturalised at",
  "Naturalised in",
  "Naturalize din",
  "Naturalized and",
  "Naturalized in",
  "Naturalize din",
  "Naturalized and",
  "Naturalized in",
  "Naturalized near",
  "Nature reserves",
  "Near border",
  "Near canteen",
  "Near edge",
  "Near foot",
  "Near footpath",
  "Near marsh",
  "Near marshy",
  "Near orchard",
  "Near parking",
  "Near path",
  "Near pond",
  "Near river",
  "Near rivulet",
  "Near road",
  "Near sea",
  "Near shore",
  "Near stream",
  "Near sugar",
  "Near the",
  "Near top",
  "Nearest cultivated",
  "New foliage",
  "Newly located",
  "Next to",
  "No indigenous",
  "No shade",
  "Noir follows",
  "Noir in",
  "North corner",
  "North facing",
  "North of",
  "North part",
  "Not common",
  "Not exposed",
  "Not fully",
  "Not on",
  "Not very",
  "Now confined",
  "Now rare",
  "Now spreading",
  "Now very",
  "Noyale to",
  "Observavi frequenter",
  "Observed in",
  "Occasinally in",
  "Occasioanl in",
  "Occasiona in",
  "Occasional along",
  "Occasional and",
  "Occasional in",
  "Occasional isolated",
  "Occasional locally",
  "Occasional on",
  "Occasional shrub",
  "Occasional throughout",
  "Occasional to",
  "Occasional tree",
  "Occasional weed",
  "Occasionally common",
  "Occasionally found",
  "Occasionally in",
  "Occasionally seen",
  "Occassional locally",
  "Occupied an",
  "Occuring on",
  "Occurring on",
  "Occurs all",
  "Occurs at",
  "Occurs in",
  "Occurs under",
  "Occurs with",
  "Often found",
  "Often harboring",
  "Often in",
  "Often planted",
  "Ombre and",
  "On a",
  "On axonopous",
  "On bamboo",
  "On bank",
  "On bare",
  "On basalt",
  "On black",
  "On border",
  "On boulder",
  "On boulders",
  "On branch",
  "On branches",
  "On broad",
  "On butress",
  "On camphor",
  "On clay",
  "On cliff",
  "On cliffs",
  "On clry",
  "On coast",
  "On compact",
  "On crest",
  "On dead",
  "On deforested",
  "On degraded",
  "On denuded",
  "On dry",
  "On earth",
  "On edge",
  "On exposed",
  "On fallen",
  "On flank",
  "On flat",
  "On forest",
  "On fork",
  "On fully",
  "On good",
  "On gravellous",
  "On gravelly",
  "On grey",
  "On ground",
  "On hard",
  "On hedge",
  "On humus",
  "On indigenous",
  "On large",
  "On laterite",
  "On lateritic",
  "On leeward",
  "On log",
  "On low",
  "On lower",
  "On margin",
  "On marshy",
  "On moist",
  "On mossy",
  "On mountains",
  "On much",
  "On native",
  "On old",
  "On open",
  "On outer",
  "On outskirt",
  "On outskirts",
  "On path",
  "On relatively",
  "On ridge",
  "On river",
  "On road",
  "On roadside",
  "On rock",
  "On rocks",
  "On rocky",
  "On rotting",
  "On rubbish",
  "On sea",
  "On sheer",
  "On shores",
  "On shrubs",
  "On slopes",
  "On sloping",
  "On small",
  "On soil",
  "On southern",
  "On steep",
  "On stone",
  "On stony",
  "On stream",
  "On summit",
  "On the",
  "On this",
  "On tree",
  "On trees",
  "On trunk",
  "On trunks",
  "On upper",
  "On vertical",
  "On very",
  "On virtually",
  "On volcanic",
  "On wall",
  "On way",
  "On western",
  "On westward",
  "On windswept",
  "On windward",
  "One colony",
  "One example",
  "One individual",
  "One mature",
  "One specimen",
  "Only flower",
  "Only flowers",
  "Only fruits",
  "Open dry",
  "Open forest",
  "Open glade",
  "Open grass",
  "Open grassy",
  "Open habitat",
  "Open heath",
  "Open heathland",
  "Open marshy",
  "Open rocky",
  "Open sedge",
  "Open shrubby",
  "Open site",
  "Open sites",
  "Open situation",
  "Open situations",
  "Open slopes",
  "Open space",
  "Or at",
  "Orchid growing",
  "Ornamental in",
  "Other exotics",
  "Other ferns",
  "Other native",
  "Other plants",
  "Other species",
  "Outside the",
  "Over canopy",
  "Over ground",
  "Over laterite",
  "Overhanging cave",
  "Page and",
  "Pamplemousses and",
  "Parasite on",
  "Particularly at",
  "Particularly in",
  "Pastures at",
  "Patch of",
  "Patches of",
  "Patchy disturbed",
  "Path along",
  "Path in",
  "Path leading",
  "Path through",
  "Pathside grass",
  "Penetrating into",
  "Petrin forest",
  "Petrin in",
  "Petrin scrub",
  "Petrin type",
  "Piton de",
  "Piton du",
  "Plaine des",
  "Plant climbing",
  "Plant collected",
  "Plant found",
  "Plant fully",
  "Plant growing",
  "Plant grows",
  "Plant not",
  "Plant rooted",
  "Plant situated",
  "Planted along",
  "Planted as",
  "Planted by",
  "Plants are",
  "Plants growing",
  "Plants in",
  "Plants raised",
  "Plateau forest",
  "Plateau with",
  "Pointe aux",
  "Pole forest",
  "Pouce a",
  "Pouce et",
  "Pouce dicta",
  "Pousse en",
  "Present also",
  "Primary association",
  "Primary climax",
  "Primary dry",
  "Primary evergreen",
  "Primary forest",
  "Primary formation",
  "Pristine rain",
  "Pristine rainforest",
  "Private garden",
  "Probably vulnerable",
  "Prostrate in",
  "Public beach",
  "Quite rare",
  "Railway line",
  "Railway tracks",
  "Rainfall ca",
  "Rare in",
  "Rare locally",
  "Rare on",
  "Rather exposed",
  "Rather rare",
  "Rather scarce",
  "Ravine shaded",
  "Ravine with",
  "Reasonable preserved",
  "Red clay",
  "Red earth",
  "Reduit gardens",
  "Region of",
  "Regions chaudes",
  "Regions of",
  "Relatively common",
  "Relatively undisturbed",
  "Relatively uninvaded",
  "Relict area",
  "Relict indigenous",
  "Relict of",
  "Relict patch",
  "Remains of",
  "Remnant native",
  "Remnant of",
  "Remnants of",
  "Restricted to",
  "Ribbon fern",
  "Rice field",
  "Rich humus",
  "Ridge summit",
  "Ridge with",
  "River and",
  "River bank",
  "River district",
  "River region",
  "River reserves",
  "River side",
  "River to",
  "Riverside and",
  "Riverside boulders",
  "Riverside stones",
  "Riviere de",
  "Riviere des",
  "Rivurine or",
  "Road between",
  "Road from",
  "Road side",
  "Road through",
  "Roadside and",
  "Roadside cutting",
  "Roadside grassy",
  "Roadside tree",
  "Roadside weed",
  "Roadsides and",
  "Roches where",
  "Rock cliff",
  "Rock covering",
  "Rock insterstices",
  "Rock track",
  "Rocks above",
  "Rockslabs and",
  "Rocky coast",
  "Rocky escarpments",
  "Rocky foreshore",
  "Rocky forested",
  "Rocky ground",
  "Rocky hill",
  "Rocky hillside",
  "Rocky locality",
  "Rocky ridge",
  "Rocky seaside",
  "Rocky site",
  "Rocky slopes",
  "Rocky soil",
  "Rocky volcanic",
  "Rooted in",
  "Rooting between",
  "Rooting in",
  "Rooting with",
  "Roots in",
  "Rough grassy",
  "Rough scrub",
  "Round the",
  "Routing among",
  "Rubbish dump",
  "Rubiaceae invaded",
  "Rubiaceae much",
  "Rubiaceae over",
  "Sandy beach",
  "Sandy shore",
  "Sapotaceae and",
  "Sapotaceae as",
  "Sapotaceae association",
  "Sapotaceae canopy",
  "Sapotaceae dominant",
  "Sapotaceae dominat",
  "Sapotaceae dominated",
  "Sapotaceae dry",
  "Sapotaceae etc",
  "Sapotaceae forest",
  "Sapotaceae formation",
  "Sapotaceae invaded",
  "Sapotaceae over",
  "Sapotaceae primary",
  "Sapotaceae rich",
  "Sapotaceae spp",
  "Sapotaceae wet",
  "Sappotaceae etc",
  "Savannahs on",
  "Scandant climber",
  "Scandent at",
  "Scarce locally",
  "Scatter isolated",
  "Scattered trees",
  "Scrambler on",
  "Scrambling in",
  "Scrambling over",
  "Scrub land",
  "Scrub vegetation",
  "Scrub with",
  "Scrubland with",
  "Sea level",
  "Seaside on",
  "Seconadry forest",
  "Secondary forest",
  "Secondary foret",
  "Secondary scrub",
  "Secondary scrubland",
  "Secondary thicket",
  "Secondary thorn",
  "Sedge forming",
  "Sedge growing",
  "Sedge rooting",
  "Sedge swamp",
  "Seedlings and",
  "Seedlings growing",
  "Seedlings of",
  "Seems to",
  "Seen on",
  "Semi deciduous",
  "Semideciduous dry",
  "Several dry",
  "Several individuals",
  "Several trees",
  "Sgrowing on",
  "Shaddy area",
  "Shade of",
  "Shady bank",
  "Shady ditch",
  "Shady habitat",
  "Shady humid",
  "Shady moist",
  "hady moist",
  "Shady native",
  "Shady places",
  "Shady ravine",
  "Shady site",
  "Shady sites",
  "Shallow bay",
  "Shallow marshy",
  "Shallow rocky",
  "Shallow swamp",
  "Sheltered behind",
  "Shrub in",
  "Shrub naturalized",
  "Shrubbery vegetation",
  "Shurb in",
  "Side of",
  "Single individual",
  "Site with",
  "Six clumps",
  "Slightly invaded",
  "Slope ca",
  "Slopes in",
  "Slopes of",
  "Sloping and",
  "Small clumps",
  "Small colony",
  "Small ground",
  "Small patch",
  "Small plant",
  "Small population",
  "Small prostrate",
  "Small relict",
  "Small roadside",
  "Small stream",
  "Small tufts",
  "Soil appearing",
  "Soil full",
  "Soil more",
  "Soil shallow",
  "Soil unweathered",
  "Sol sale",
  "Solitary in",
  "Some branches",
  "Some indigenous",
  "Some large",
  "Some of",
  "Some patches",
  "Some plants",
  "Some regeneration",
  "Sometimes cultivated",
  "Sometimes in",
  "Sometimes with",
  "Somewhat nearer",
  "Souillac between",
  "Souillac cemetery",
  "Sous bois",
  "South coast",
  "South of",
  "South west",
  "Southern flanks",
  "Sparse clump",
  "Species known",
  "Species nearby",
  "Specimen growing",
  "Spores absent",
  "Spores present",
  "Sporling growing",
  "Spreading from",
  "Sprouting from",
  "Spur forest",
  "Sream bank",
  "Sriana near",
  "Standing water",
  "Steam side",
  "Steep dry",
  "Steep hillside",
  "Steep rocky",
  "Steep slope",
  "Steep slopes",
  "Steep south",
  "Steep stony",
  'Stony bare',
  "Stony ground",
  "Strand species",
  "Strand vegetation",
  "Stream and",
  "Stream bank",
  "Stream banks",
  "Stream near",
  "Stream of",
  "Stream side",
  "Sttep forested",
  "Stump of",
  "Stunted and",
  "Stunted forest",
  "Stunted thicket",
  "Sub humid",
  "Subhumid forest",
  "Subhumid forests",
  "Sugar cane",
  "Summit ridge",
  "Sun or",
  "Sun rocky",
  "Sunny sea",
  "Sunny site",
  "Sunny situation",
  "Sur crete",
  "Sur forte",
  "Sur la",
  "Sur le",
  "Sur les",
  "Sur toutes",
  "Sus bois",
  "Swampy valley",
  "Tall tufted",
  "Tamarin and",
  "Tea plantation",
  "Temperature of",
  "Terrestrial fern",
  "Terrestrial growing",
  "Terrestrial species",
  "The forest",
  "The trail",
  "Thirteen clumps",
  "This individual",
  "This is",
  "This liana",
  "This plant",
  "This species",
  "Those growing",
  "Tifted in",
  "To salt",
  "Together with",
  "Top strata",
  "Totally degraded",
  "Trailing herb",
  "Transitional evergreen",
  "Tree by",
  "Tree growing",
  "Tree in",
  "Tree thicket",
  "Tufted with",
  "Twining around",
  "Twining over",
  "Two leaning",
  "Two smaller",
  "Typical of",
  "Una inter",
  "Under canopy",
  "Under cover",
  "Under intermediate",
  "Under shade",
  "Under the",
  "Under tree",
  "Undershrub in",
  "Underside of",
  "University of",
  "Upland bogs",
  "Upland climax",
  "Upland forest",
  "Upland forests",
  "Upland heath",
  "Upland marshes",
  "Upland native",
  "Upland pasture",
  "Upland regions",
  "Upland scrub",
  "Upland shrub",
  "Upland stream",
  "Upland thickets",
  "Upland turf",
  "Upland woods",
  "Uplands and",
  "Uplands generally",
  "Uplands high",
  "Uplands in",
  "Used as",
  "Usually dry",
  "Usually found",
  "Usually growing",
  "Usually more",
  "Usually on",
  "Usually pendent",
  "Usually riverine",
  "Usually with",
  "Vacoas in",
  "Vacoas ridge",
  "Valley forest",
  "Valley slopes",
  "Valley with",
  "Vaughan annotation",
  "Vegetable garden",
  "Vegetation cover",
  "Vegetation incl",
  "Vegetation is",
  "Vegetation low",
  "Vegetation slightly",
  "Vegetation totally",
  "Vegetation very",
  "Verge of",
  "Vertical moist",
  "Vertical rock",
  "Very close",
  "Very common",
  "Very degraded",
  "Very dense",
  "Very disturbed",
  "Very exposed",
  "Very good",
  "Very high",
  "Very humid",
  "Very invaded",
  "Very little",
  "Very localised",
  "Very mossy",
  "Very much",
  "Very occasional",
  "Very recently",
  "Very rocky",
  "Very shady",
  "Very steep",
  "Very wet",
  "Very widely",
  "Vey common",
  "Volcanic crater",
  "Vulnerable to",
  "Waste ground",
  "Waste land",
  "Wasteland near",
  "Water saturated",
  "Waterfalls opposite",
  "Weed by",
  "Weed common",
  "Weed growing",
  "Weed in",
  "Weed of",
  "Weed on",
  "Weeded area",
  "Weedy species",
  "Well preserved",
  "West of",
  "West part",
  "West slopes",
  "Western mountain",
  "Western range",
  "Wet forest",
  "Wet ground",
  "Wet primary",
  "Where is",
  "White or",
  "Whole colony",
  "Wide flattish",
  "Widely distributed",
  "Widely naturalized",
  "Widely planted",
  "Wild cane",
  "Windy site",
  "With hygrophilous",
  "With indigenous",
  "With low",
  "With scattered",
  "Within a",
  "Woodland forest",
  "Woody liane",
  "Young pine"
)

extracted_data <- extracted_data |>
  filter(!spp %in% non_species)

rm(non_species, unique_species) # Tidy

glimpse(extracted_data)
glimpse(herb)

# Mark and align original data, then combine
herb <- herb |>
  mutate(
    source = "H.original"
  ) |>
  select(-c("country", "major"))

# check weather column name matches
# 1. Get all unique column names from both datasets
all_columns <- union(names(herb), names(extracted_data))

# 2. Create the comparison table
comparison_table <- data.frame(
  Column_Name = all_columns,
  In_DF1 = all_columns %in% names(herb),
  In_DF2 = all_columns %in% names(extracted_data)
)

print(comparison_table)

updated_herb <- bind_rows(herb, extracted_data) |>
  arrange(id)

rm(extracted_data, herb, comparison_table, all_columns) # Tidy

# =============================================================================
# STEP 6 – Remove incomplete species name
# =============================================================================

unique_species <- updated_herb %>%
  filter(source == "H.extract") %>%
  select(spp) %>%
  distinct() %>%
  arrange(spp)

inc_species <- c(
  "Abrodictyum sp",
  "Acacia scrub",
  "Acalypha sp",
  "Albizia dominant",
  "Albizia etc",
  "Albizzia dominant",
  "Ampelopteris and",
  "Antidesma in",
  "Antrophium and",
  "Antrophyum and",
  "Ardisia sp",
  "Ardisia spp",
  "Badula much",
  "Bambusa sp",
  "Blechum and",
  "Bougainvillea sp",
  "Bruguera on",
  "Bulbophyllum found",
  "Bulbophyllum sp",
  "Calophyllum abundant",
  "Calophyllum dominant",
  "Calophyllum formation",
  "Calophyllum here",
  "Calophyllum sp",
  "Calophyllum wet",
  "Canna sp",
  "Casuarina and",
  "Casuarina plantation",
  "Casuarina plantations",
  "Casuarina sp",
  "Chassalia sp",
  "Cinnamomum sp",
  "Citrus sp",
  "Cladium and",
  "Coastal mangrove",
  "Colophane tree",
  "Crete s",
  "Croton etc",
  "Cyathea ca",
  "Cynanchum sp",
  "Cynorkis sp",
  "Dianella sp",
  "Digitaria plains",
  "Diospyros and",
  "Diospyros dominant",
  "Diospyros dry",
  "Diospyros etc",
  "Diospyros much",
  "Diospyros primary",
  "Diospyros sp",
  "Diospyros spp",
  "Diospyros trunk",
  "Dracaena formation",
  "Dracaena sp",
  "Dracalma etc",
  "Elaeodendron dominant",
  "Elaeodendron tree",
  "Elaphoglossum and",
  "Erigeron sp",
  "Erythroxylon and",
  "Eucalyptus and",
  "Eucalyptus area",
  "Eucalyptus mainly",
  "Eucalyptus on",
  "Eucalyptus plantation",
  "Eucalyptus sp",
  "Eucalyptus tree",
  "Eugenia and",
  "Eugenia association",
  "Eugenia formation",
  "Eugenia invaded",
  "Eugenia present",
  "Eugenia shrub",
  "Eugenia sp",
  "Eugenia spp",
  "Festuca spp",
  "Fimbristylis spp",
  "Fimbristylis and",
  "Flacourtia and",
  "Furcraea and",
  "Furcreae and",
  "Fureraea and",
  "Furerea scrub",
  "Gaertnera and",
  "Gaertnera sp",
  "Gaetnera sp",
  "Gaetnera species",
  "Gaetnera spp",
  "Garcinia sp",
  "Gastonia etc",
  "Glacis between",
  "Graminae and",
  "Graminae often",
  "Gramineae in",
  "Helichrysum and",
  "Helichrysum etc",
  "Helichrysum thicket",
  "Hymenophylllum sp",
  "Hymenophyllum sp",
  "Hymenophyllum spp",
  "Hyptis sp",
  "In Sideroxylon",
  "Ipomoea sp",
  "Ischaemum sp",
  "Ixora sp",
  "Jumellea sp",
  "Juncus sp",
  "Juniper trees",
  "Justicia sp",
  "Kalanchoe sp",
  "Labourdonaisia low",
  "Labourdonaisia sp",
  "Labourdonnaisia and",
  "Labourdonnaisia association",
  "Labourdonnaisia low",
  "Labourdonnaisia tree",
  "Leguminosae dominant",
  "Leucaena scrub",
  "Leucaena shrubs",
  "Leuceuna thicket",
  "Listea etc",
  "Litsea and",
  "Litsea scrubland",
  "Litsea shrubs",
  "Litsea sp",
  "Litsea trees",
  "Lobelia sp",
  "Ludwigia sp",
  "Lwinothers and",
  "Lycopodium sp",
  "Lycopodium spp",
  "Lygodium covering",
  "Madagascariensis clumps",
  "Mangrove community",
  "Mangrove forest",
  "Mangrove swamp",
  "Mangrove swamps",
  "Memecylon due",
  "Memecylon sp",
  "Microsorium plant",
  "Mimusops and",
  "Mimusops sp",
  "Monimiacae highly",
  "Monimiaceae highly",
  "Monimiastrum sp",
  "Monmiaceae highly",
  "Mousse m",
  "Myrtaceae and",
  "Nasturtiums along",
  "Nephrolepis ca",
  "Ocotea sp",
  "Oplismenus sp",
  "Pandanus clump",
  "Pandanus colony",
  "Pandanus grove",
  "Pandanus groves",
  "Pandanus growing",
  "Pandanus marsh",
  "Pandanus on",
  "Pandanus plot",
  "Pandanus sp",
  "Pandanus species",
  "Pandanus spp",
  "Pandanus swamp",
  "Pandanus thicket",
  "Paspalum sp",
  "Peperomia sp",
  "Pine tree",
  "Pine woods",
  "Pinus sp",
  "Pinus spp",
  "Pine plantation",
  "Piper sp",
  "Polyscias sp",
  "Polyscias trunk",
  "Psiadia bushes",
  "Psiadia sp",
  "Psidia bushes",
  "Pyrostria sp",
  "Rhamnus and",
  "Rhamnus with",
  "Rhizomatous in",
  "Rhizome in",
  "Rubus and",
  "Rubus sp",
  "Rubus with",
  "Saccharum sp",
  "Scutia and",
  "Selaginella in",
  "Selaginella sp",
  "Sellaginella sp",
  "Sesuvium form",
  "Sesuvium growing",
  "Sesuvium vary",
  "Sideroxylon and",
  "Sideroxylon association",
  "Sideroxylon community",
  "Sideroxylon dominant",
  "Sideroxylon forest",
  "Sideroxylon formation",
  "Sideroxylon low",
  "Sideroxylon onereum",
  "Sideroxylon spp",
  "Sideroxylon subclimax",
  "Sideroxylon thciket",
  "Sideroxylon thicket",
  "Sideroxylon trees",
  "Sideroxylon wet",
  "Sorghum sp",
  "Spermacoce sp",
  "Sphagmum marsh",
  "Sphagnum mats",
  "Sphagnum moss",
  "Sporobolus and",
  "Sporobolus from",
  "Stenotaphrum lawn",
  "Syderoxylon thicket",
  "Syzygium sp",
  "Syzygium spp",
  "Tadehagi sp",
  "Tecoma forest",
  "Tecoma stans",
  "Terminalia etc",
  "Thicket transitional",
  "Typha marsh",
  "Typha swamp",
  "Typhra marsh",
  "Walkeri and",
  "Wikstroemia and",
  "Xyris sp",
  "Zoisia grass"
)

updated_herb <- updated_herb |>
  filter(!spp %in% inc_species)

rm(inc_species) # Tidy

# =============================================================================
# STEP 7 – Update incomplete species name (extracted data)
# =============================================================================

unique_species <- updated_herb %>%
  filter(source == "H.extract") %>%
  select(spp) %>%
  distinct() %>%
  arrange(spp)

# Create vector for consistent naming
species_replacement <- tribble(
  ~original_name                    , ~corrected_name                   ,
  "Acanthophenix rubra"             , "Acanthophoenix rubra"            ,
  "Aeranthes arachnitis"            , "Aeranthes arachnites"            ,
  "Allophyllus borbonicum"          , "Allophylus borbonicum"           ,
  "Allophyllus borbonicus"          , "Allophylus borbonicum"           ,
  "Allophylus borbonicus"           , "Allophylus borbonicum"           ,
  "Ardisia creanata"                , "Ardisia crenata"                 ,
  "Asplenium dancifolium"           , "Asplenium daucifolium"           ,
  "Asplenium polydon"               , "Asplenium polyodon"              ,
  "Asplenium polyodont"             , "Asplenium polyodon"              ,
  "Bertiera zaluziana"              , "Bertiera zaluzania"              ,
  "Bertira zaluzaniana"             , "Bertiera zaluzania"              ,
  "Boerhavia concinna"              , "Boerhavia coccinea"              ,
  "Bothrichloa pertusa"             , "Bothriochloa pertusa"            ,
  "Bracharia umbellate"             , "Brachiaria umbellata"            ,
  "Bruguieria gymnorhiza"           , "Bruguiera gymnorhiza"            ,
  "Callophyllum eputamen"           , "Calophyllum eputamen"            ,
  "Calophyllum tacamahac"           , "Calophyllum tacamahaca"          ,
  "Camelia sinensis"                , "Camellia sinensis"               ,
  "Camphor tree"                    , "Cinnamomum camphora"             ,
  "Chinese latania"                 , "Latania chinensis"               ,
  "Chinese goyava"                  , "Psidium cattleianum"             ,
  "Chinese guava"                   , "Psidium cattleianum"             ,
  "Goyava etc"                      , "Psidium cattleianum"             ,
  "Psidium guajava"                 , "Psidium cattleianum"             ,
  "Psidium guava"                   , "Psidium cattleianum"             ,
  "Psidium guayava"                 , "Psidium cattleianum"             ,
  "Psidium gujavea"                 , "Psidium cattleianum"             ,
  "Psidium sp"                      , "Psidium cattleianum"             ,
  "Psidium thicket"                 , "Psidium cattleianum"             ,
  "Psidium thickets"                , "Psidium cattleianum"             ,
  "Jamrosa tree"                    , "Syzygium jambos"                 ,
  "Eugenia jambos"                  , "Syzygium jambos"                 ,
  "Sygium jambos"                   , "Syzygium jambos"                 ,
  "Eugenia psiodiodea"              , "Eugenia psidioidea"              ,
  "Faujasiopis flexuosa"            , "Faujasiopsis flexuosa"           ,
  "Ficus mauritianus"               , "Ficus mauritiana"                ,
  "Flacourtia idica"                , "Flacourtia indica"               ,
  "Gaertnera psychotrioides"        , "Gaertnera psicotrioides"         ,
  "Gaertnera psycothrioides"        , "Gaertnera psicotrioides"         ,
  "Geniostoma pedunculatum"         , "Geniostoma pedunculata"          ,
  "Geniostoma penduculata"          , "Geniostoma pedunculata"          ,
  "Haematoxylum campechianum"       , "Haematoxylon scrub"              ,
  "Harungana madagascariense"       , "Harungana madagascariensis"      ,
  "Harungana madascariensis"        , "Harungana madagascariensis"      ,
  "Ipomea pes"                      , "Ipomoea pes-caprae"              ,
  "Ipomoea pescaprae"               , "Ipomoea pes-caprae"              ,
  "Ipomoea pres"                    , "Ipomoea pes-caprae"              ,
  "Ipomoea pse"                     , "Ipomoea pes-caprae"              ,
  "Labourdannaisia callophylloides" , "Labourdonnaisia calophylloides"  ,
  "Labourdannaisia callophyloides"  , "Labourdonnaisia calophylloides"  ,
  "Labourdonnasia glauca"           , "Labourdonnaisia glauca"          ,
  "Labourdonassia glaca"            , "Labourdonnaisia glauca"          ,
  "Labourdonnaisia glabra"          , "Labourdonnaisia glauca"          ,
  "Latana camara"                   , "Lantana camara"                  ,
  "Leea guineesis"                  , "Leea guineensis"                 ,
  "Leea guinense"                   , "Leea guineensis"                 ,
  "Ligustrum robusrtum"             , "Ligustrum robustum"              ,
  "Ligustrum robustrum"             , "Ligustrum robustum"              ,
  "Ligustrum robustu"               , "Ligustrum robustum"              ,
  "Ligustrum walkeri"               , "Ligustrum robustum"              ,
  "Privet and"                      , "Ligustrum robustum"              ,
  "Litsea glutinousa"               , "Litsea glutinosa"                ,
  "Livistonia chinensis"            , "Livistona chinensis"             ,
  "Ludia mauriatiana"               , "Ludia mauritiana"                ,
  "Ludwigia octavalis"              , "Ludwigia octovalvis"             ,
  "Ludwigia stonolifera"            , "Ludwigia stolonifera"            ,
  "Macarnaga mauririana"            , "Macaranga mauritiana"            ,
  "Machaerina iridifolium"          , "Machaerina iridifolia"           ,
  "Manglier vert"                   , "Sideroxylon cinereum"            ,
  "Margaritoria anomala"            , "Margaritaria anomala"            ,
  "Mayyenus pyria"                  , "Maytenus pyria"                  ,
  "Memecyclon conketum"             , "Memecylon conketum"              ,
  "Memecylon cordatum"              , "Memecylon conketum"              ,
  "Microsorium punctatum"           , "Microsorum punctatum"            ,
  "Molineaea alternifolia"          , "Molinaea alternifolia"           ,
  "Nephrolelis biserrate"           , "Nephrolepis biserrata"           ,
  "Nephrolepis biserrate"           , "Nephrolepis biserrata"           ,
  "Nephrolepsis bisserrata"         , "Nephrolepis biserrata"           ,
  "Nephrolepuis biserrate"          , "Nephrolepis biserrata"           ,
  "Nuxia verticellata"              , "Nuxia verticillata"              ,
  "Nuxia verticilata"               , "Nuxia verticillata"              ,
  "Nuxia verticulata"               , "Nuxia verticillata"              ,
  "Oberonia distichia"              , "Oberonia disticha"               ,
  "Orfilea neuradiana"              , "Orfilea neraudiana"              ,
  "Ossaea marginat"                 , "Ossaea marginata"                ,
  "Ossea marginata"                 , "Ossaea marginata"                ,
  "Paedaria foetida"                , "Paederia foetida"                ,
  "Pandanus carmichaeli"            , "Pandanus carmichaelii"           ,
  "Panadanus eydouxia"              , "Pandanus eydouxia"               ,
  "Pandanus weihei"                 , "Pandanus wiehei"                 ,
  "Philippia brachyphylla"          , "Erica"                           ,
  "Phillipia brachyphylla"          , "Erica"                           ,
  "Philyca over"                    , "Phylica"                         ,
  "Phylica nitica"                  , "Phylica nitida"                  ,
  "Phyllanthus phyllireifolius"     , "Phyllanthus phillyreifolius"     ,
  "Phyllanthus pyrifolius"          , "Phyllanthus phillyreifolius"     ,
  "Phymatosonus scolopendria"       , "Phymatosorus scolopendria"       ,
  "Pinus ellioti"                   , "Pinus elliottii"                 ,
  "Pinus ellitotti"                 , "Pinus elliottii"                 ,
  "Pithecellobium dulcis"           , "Pithecellobium dulce"            ,
  "Pithecelobium dulce"             , "Pithecellobium dulce"            ,
  "Pithecelobium ungis"             , "Pithecellobium unguis"           ,
  "Pithecelobium unguis"            , "Pithecellobium unguis"           ,
  "Pittosporum fernigieum"          , "Pittosporum ferrugineum"         ,
  "Pittosporum sencia"              , "Pittosporum senacia"             ,
  "Pleurostilia leucocarpa"         , "Pleurostylia leucocarpa"         ,
  "Polycias gracilis"               , "Polyscias gracilis"              ,
  "Pouzolzia laevigata"             , "Pousolzia laevigata"             ,
  "Premna serratifolia"             , "Premna obtusifolia"              ,
  "Protim obtusifolium"             , "Protium obtusifolium"            ,
  "Protium and"                     , "Protium obtusifolium"            ,
  "Protium obtustifolium"           , "Protium obtusifolium"            ,
  "Psiloxylum mauritianum"          , "Psiloxylon mauritianum"          ,
  "Psyloxylon mauritianum"          , "Psiloxylon mauritianum"          ,
  "Psyloxylum mauritianum"          , "Psiloxylon mauritianum"          ,
  "Ravenal madagascariensis"        , "Ravenala madagascariensis"       ,
  "Ravenala and"                    , "Ravenala madagascariensis"       ,
  "Ravenala as"                     , "Ravenala madagascariensis"       ,
  "Ravenala madagsacriensis"        , "Ravenala madagascariensis"       ,
  "Ravenala madascariensis"         , "Ravenala madagascariensis"       ,
  "Ravenala nmadagascariensis"      , "Ravenala madagascariensis"       ,
  "Ravenala thicket"                , "Ravenala madagascariensis"       ,
  "Ravenela trees"                  , "Ravenala madagascariensis"       ,
  "Rhizopohora mucronata"           , "Rhizophora mucronata"            ,
  "Rubus alceifolus"                , "Rubus alceifolius"               ,
  "Rumhora adiantiformis"           , "Rumohra adiantiformis"           ,
  "Rumohra and"                     , "Rumohra adiantiformis"           ,
  "Scaevola and"                    , "Scaevola taccada"                ,
  "Scaevola near"                   , "Scaevola taccada"                ,
  "Scaevola shrub"                  , "Scaevola taccada"                ,
  "Schinus terebenthifolia"         , "Schinus terebinthifolia"         ,
  "Schinus terebinthifolius"        , "Schinus terebinthifolia"         ,
  "Schinus terebnthifolius"         , "Schinus terebinthifolia"         ,
  "Securinega dominant"             , "Securinega durissima"            ,
  "Securinega durisimma"            , "Securinega durissima"            ,
  "Securinega etc"                  , "Securinega durissima"            ,
  "Selaginella fruticose"           , "Selaginella fruticulosa"         ,
  "Selaginella fruticulose"         , "Selaginella fruticulosa"         ,
  "Selaginella frutilucosa"         , "Selaginella fruticulosa"         ,
  "Senecio sp"                      , "Senecio lamarckianus"            ,
  "Stadmannia oppositifolia"        , "Stadmania oppositifolia"         ,
  "Stilingia lineata"               , "Stillingia lineata"              ,
  "Stillingia dominant"             , "Stillingia lineata"              ,
  "Stillingia thicket"              , "Stillingia lineata"              ,
  "Stillinoia marsh"                , "Stillingia lineata"              ,
  "Suriana diminant"                , "Suriana maritima"                ,
  "Suriana dominant"                , "Suriana maritima"                ,
  "Suriana dominat"                 , "Suriana maritima"                ,
  "Syzygium petrinensis"            , "Syzygium petrinense"             ,
  "Syzygium vaughnii"               , "Syzygium vaughanii"              ,
  "Syzygium vernosum"               , "Syzygium venosum"                ,
  "Tabernaemontana persicariifolia" , "Tabernaemontana perscicalifolia" ,
  "Tamarindus indicus"              , "Tamarindus indica"               ,
  "Thespesia polpunea"              , "Thespesia populnea"              ,
  "Tournefortia and"                , "Tournefortia argentea"           ,
  "Tournefortia shrub"              , "Tournefortia argentea"           ,
  "Tristemma mauritiana"            , "Tristemma mauritianum"           ,
  "Warneckia trinervis"             , "Warneckea trinervis"
)

updated_herb <- updated_herb %>%
  left_join(
    species_replacement,
    by = c("spp" = "original_name")
  ) %>%
  mutate(
    spp = coalesce(corrected_name, spp)
  ) %>%
  select(-corrected_name)

rm(species_replacement, unique_species) # Tidy

# Convert specific columns to character format  Excel sometimes shortens numbers or shows them in scientific notation
updated_herb$x <- as.character(updated_herb$x)
updated_herb$y <- as.character(updated_herb$y)

write_csv(updated_herb, "data/Herb_collection_cleaned_25-09-2023.csv")

# proceed to manual cleaning of "spp" column as precaution

# =============================================================================
# STEP 6 – Update / validate species names with Taxonstand
# =============================================================================

# install require package for naming update
devtools::install_github("ecoinfor/U.Taxonstand") # updating plant species
library(U.Taxonstand)

# read data
herb <- read.csv(
  "data/Herb_collection_cleaned_25-09-2023.csv",
  na.strings = c("", "NA")
)

# Extract unique species names that look like binomials (Genus species)
unique_spp <- final_data |>
  filter(str_detect(spp, "^[A-Z][a-z]+ [a-z]+")) |>
  distinct(spp) |>
  pull(spp)

# Run Taxonstand — may take several minutes for large lists
# corr = TRUE  : allow minor spelling corrections
# diffchar = 2 : tolerate up to 2 character differences
# max.distance = 1 : Levenshtein distance threshold
taxon_results <- TPL(
  unique_spp,
  corr = TRUE,
  diffchar = 2,
  max.distance = 1
)

# Build a clean lookup: original name → accepted name
name_lookup <- taxon_results |>
  transmute(
    spp_original = paste(Genus, Species), # original queried name
    spp_accepted = case_when(
      Taxonomic.status == "Accepted" ~ paste(New.Genus, New.Species),
      Taxonomic.status == "Synonym" ~ paste(New.Genus, New.Species),
      TRUE ~ paste(Genus, Species) # keep original if unresolved
    ),
    tax_status = Taxonomic.status,
    tax_authority = Authority
  ) |>
  filter(!is.na(spp_accepted))

# Save the full Taxonstand results for audit purposes
write_xlsx(taxon_results, "taxonstand_results.xlsx")
cat("  Saved: taxonstand_results.xlsx\n")

# Join accepted names back into the main dataset
final_data <- final_data |>
  left_join(name_lookup, by = c("spp" = "spp_original")) |>
  mutate(
    spp_updated = if_else(!is.na(spp_accepted), spp_accepted, spp)
  ) |>
  select(-spp_accepted) # keep spp (original), spp_updated (accepted), tax_status, tax_authority

write_xlsx(final_data, "herb_final.xlsx")

rm(taxon_results, name_lookup, unique_spp)

# =============================================================================
# STEP 7 – Density map of all collection points
# =============================================================================

# Keep only records with valid coordinates and convert sign based on NS/EW fields
map_data <- final_data |>
  filter(!is.na(x), !is.na(y), x != 0, y != 0) |>
  mutate(
    lon = if_else(tolower(ew) == "w", -abs(x), abs(x)),
    lat = if_else(tolower(ns) == "s", -abs(y), abs(y))
  ) |>
  filter(between(lon, -180, 180), between(lat, -90, 90)) |>
  distinct(lon, lat) # one point per unique coordinate

cat(sprintf("  Valid coordinate pairs for mapping: %d\n", nrow(map_data)))

# Base map — Mauritius region
world <- ne_countries(scale = "medium", returnclass = "sf")

# Determine bounding box with a small buffer
lon_range <- range(map_data$lon, na.rm = TRUE)
lat_range <- range(map_data$lat, na.rm = TRUE)
buf <- 0.5 # degrees buffer around the data extent

density_map <- ggplot() +
  # Country polygons
  geom_sf(data = world, fill = "grey90", colour = "grey60", linewidth = 0.3) +
  # 2-D density (filled contours)
  stat_density_2d(
    data = map_data,
    aes(x = lon, y = lat, fill = after_stat(level)),
    geom = "polygon",
    alpha = 0.75,
    contour = TRUE,
    bins = 15
  ) +
  # Individual collection points (semi-transparent)
  geom_point(
    data = map_data,
    aes(x = lon, y = lat),
    colour = "white",
    alpha = 0.25,
    size = 0.8
  ) +
  # Colour scale
  scale_fill_viridis_c(
    option = "inferno",
    name = "Density\n(collection density)",
    direction = -1
  ) +
  # Map extent
  coord_sf(
    xlim = c(lon_range[1] - buf, lon_range[2] + buf),
    ylim = c(lat_range[1] - buf, lat_range[2] + buf),
    expand = FALSE
  ) +
  # Labels
  labs(
    title = "Herbarium Collection Density",
    subtitle = sprintf("n = %d unique collection points", nrow(map_data)),
    x = "Longitude",
    y = "Latitude",
    caption = "Data source: Herbarium collection dataset"
  ) +
  theme_bw(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(colour = "grey40"),
    legend.position = "right",
    panel.grid = element_line(colour = "grey80", linewidth = 0.3)
  )

# Save the map
ggsave(
  "herbarium_density_map.png",
  plot = density_map,
  width = 10,
  height = 8,
  dpi = 300,
  bg = "white"
)

print(density_map)
